# Generated by Django 4.2.5 on 2023-09-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('goal_tempo_bpm', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('current_tempo', models.IntegerField()),
                ('audio_link', models.CharField()),
                ('start_time', models.TimeField()),
                ('last_practiced', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.excerpt')),
            ],
        ),
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchestra', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('excerpts', models.ManyToManyField(to='main_app.excerpt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
