# Generated by Django 4.2.5 on 2023-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='audio_link',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='current_tempo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='goal_tempo_bpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='last_practiced',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
