# Generated by Django 4.2.5 on 2023-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_excerpt_last_practiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excerpt',
            name='goal_tempo_type',
            field=models.CharField(choices=[('E', 'Eighth Note'), ('Q', 'Quarter Note'), ('H', 'Half Note'), ('W', 'Whole Note')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='audio_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='current_tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='goal_tempo_bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
