# Generated by Django 4.2.5 on 2023-09-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_audition_excerpts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audition',
            name='excerpts',
        ),
        migrations.AddField(
            model_name='excerpt',
            name='auditions',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.audition'),
        ),
    ]
