# Generated by Django 4.2.5 on 2023-09-23 21:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_audition_excerpts_excerpt_auditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerpt',
            name='audio_link',
        ),
        migrations.AddField(
            model_name='excerpt',
            name='audio_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), default=None, size=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='auditions',
            field=models.ManyToManyField(to='main_app.audition'),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='goal_tempo_type',
            field=models.CharField(choices=[('E', '♪ (eighth)'), ('Q', '♩ (quarter)'), ('H', '(half)'), ('W', '(whole)')], default='Q', max_length=1),
        ),
    ]
