# Generated by Django 4.2.5 on 2023-09-23 23:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_excerpt_start_time_excerpt_start_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, help_text='in same order as links', null=True, size=3, verbose_name='excerpt time'),
        ),
    ]
