# Generated by Django 4.2.5 on 2023-09-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_excerpt_auditions_alter_excerpt_instrument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excerpt',
            old_name='auditions',
            new_name='audition',
        ),
    ]
