# Generated by Django 4.2.5 on 2023-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_excerpt_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='audio_links',
            field=models.TextField(blank=True, help_text='separate by commas', null=True, verbose_name='Spotify Links'),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='start_times',
            field=models.CharField(blank=True, help_text='in same order as links', null=True, verbose_name='excerpt time'),
        ),
    ]
