# Generated by Django 4.2.5 on 2023-09-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_excerpt_audio_links_alter_excerpt_start_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('audition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.audition')),
            ],
        ),
    ]
