# Generated by Django 4.2.5 on 2023-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_goal_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerpt',
            name='goal_tempo_type',
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='start_times',
            field=models.CharField(blank=True, help_text='separated by commas in same order as links above, ', null=True, verbose_name='excerpt time (mm:ss)'),
        ),
    ]
